---
- name: Build & Deploy Docker Container
  hosts: webserver
  gather_facts: false
  remote_user: root
  tasks:
    - name: Copy the files to remote server
      become: true
      copy:
        src: /var/lib/jenkins/workspace/ansible-jenkins-pipeline
        dest: ~/project
        
    - name: Building Docker Image
        docker_image:
          name: mico:latest
          build:
            path: ~/project
          state: present
          
     - name: Creating the container
       docker_container:
         name: mico-container
         image: mico:laters
         ports:
           - "80:80"
         state: started